CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER 'mgs' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON  wordpress.* to 'mgs'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';
FLUSH PRIVILEGES;
exit